<a href="https://colab.research.google.com/github/ylmgrbzz/Deep-Learning-Projects-With-Keras-TensorFlow-PyTorch/blob/main/Dimension_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
veriler = pd.read_csv('Wine.csv')


In [7]:
veriler

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [8]:
X = veriler.iloc[:, 0:13].values
y = veriler.iloc[:, 13].values

In [10]:
from sklearn.model_selection import train_test_split


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [12]:
from sklearn.preprocessing import StandardScaler


In [13]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.decomposition import PCA


In [15]:
pca = PCA(n_components = 2)


In [16]:
X_train2 = pca.fit_transform(X_train)
X_test2 = pca.transform(X_test)


In [17]:
from sklearn.linear_model import LogisticRegression


In [18]:
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [20]:
classifier2 = LogisticRegression(random_state=0)
classifier2.fit(X_train2,y_train)

LogisticRegression(random_state=0)

In [21]:
lassifier2 = LogisticRegression(random_state=0)
classifier2.fit(X_train2,y_train)


LogisticRegression(random_state=0)

In [22]:
y_pred = classifier.predict(X_test)

y_pred2 = classifier2.predict(X_test2)

In [23]:
from sklearn.metrics import confusion_matrix


In [24]:
print('gercek / PCAsiz')
cm = confusion_matrix(y_test,y_pred)
print(cm)

gercek / PCAsiz
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


In [25]:
print("gercek / pca ile")
cm2 = confusion_matrix(y_test,y_pred2)
print(cm2)

gercek / pca ile
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


In [26]:
print('pcasiz ve pcali')
cm3 = confusion_matrix(y_pred,y_pred2)
print(cm3)

pcasiz ve pcali
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


In [27]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA


In [28]:
lda = LDA(n_components = 2)


In [29]:
X_train_lda = lda.fit_transform(X_train,y_train)
X_test_lda = lda.transform(X_test)

In [30]:
classifier_lda = LogisticRegression(random_state=0)
classifier_lda.fit(X_train_lda,y_train)

LogisticRegression(random_state=0)

In [31]:
y_pred_lda = classifier_lda.predict(X_test_lda)


In [32]:
print('lda ve orijinal')
cm4 = confusion_matrix(y_pred,y_pred_lda)
print(cm4)

lda ve orijinal
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
